
setwd("/Users/kahrens/MyProjects/pystacked")

##############################################################################
### pystacked2.ado = pystacked1.ado + pystacked.py                         ###
##############################################################################

# Define file paths
ado1 <- "pystacked1.ado"
ado2 <- "pystacked2.ado"
pyfile <- "pystacked.py"

# Read the contents of pystacked1.ado
ado1_lines <- readLines(ado1, warn = FALSE)

# Replace the line defining the program
ado1_lines <- gsub(
  pattern = "^program define pystacked1, eclass$",
  replacement = "program define pystacked2, eclass",
  x = ado1_lines
)

ado1_lines[4] <-
  "*! pystacked2 = uses python code appended to the file"
ado1_lines[5] <-
  ""
ado1_lines[7] <-
  "// do not edit this file manually; edit pystacked1.ado, then run R script"

ado1_lines <- gsub(
  pattern = "//\\s*load core python code",
  replacement = "/* // load core python code",
  x = ado1_lines
)

ado1_lines <- gsub(
  pattern = "//\\s*end load core python code",
  replacement = "*/ // end load core python code",
  x = ado1_lines
)


# Read the contents of pystacked.py
py_lines <- readLines(pyfile, warn = FALSE)

# Combine the modified ado content with the Python code
output_lines <- c(ado1_lines,
                  "",
                  "* --- Python code appended below ---",
                  "python:",
                  py_lines,
                  "end")

# Write to pystacked2.ado
writeLines(output_lines, ado2)

cat("✅ pystacked2.ado created successfully.\n")

##############################################################################
### pystacked2_p.ado = pystacked1_p.ado + pystacked_p.py                   ###
##############################################################################

# Define file paths
ado1_p <- "pystacked1_p.ado"
ado2_p <- "pystacked2_p.ado"
pyfile_p <- "pystacked_p.py"

# Read the contents of pystacked1_p.ado
ado1_p_lines <- readLines(ado1_p, warn = FALSE)

# Replace the line defining the program
ado1_p_lines <- gsub(
  pattern = "^program define pystacked1_p, rclass$",
  replacement = "program define pystacked2_p, rclass",
  x = ado1_p_lines
)

ado1_p_lines[4] <-
  "*! pystacked2_p = uses python code appended to the file"
ado1_p_lines[5] <-
  ""
ado1_p_lines[6] <-
  "// do not edit this file manually; edit pystacked1_p.ado, then run R script"

# Comment out the python import (python code is appended below instead)
ado1_p_lines <- gsub(
  pattern = "^(\\s*)python: from pystacked_p import \\*",
  replacement = "\\1// python: from pystacked_p import *",
  x = ado1_p_lines
)

# Read the contents of pystacked_p.py
py_p_lines <- readLines(pyfile_p, warn = FALSE)

# Combine the modified ado content with the Python code
output_lines_p <- c(ado1_p_lines,
                    "",
                    "* --- Python code appended below ---",
                    "python:",
                    py_p_lines,
                    "end")

# Write to pystacked2_p.ado
writeLines(output_lines_p, ado2_p)

cat("✅ pystacked2_p.ado created successfully.\n")
