
setwd("/Users/kahrens/MyProjects/pystacked")

# Define file paths
ado1 <- "pystacked1.ado"
ado2 <- "pystacked2.ado"
pyfile <- "pystacked.py"

# Read the contents of pystacked1.ado
ado1_lines <- readLines(ado1, warn = FALSE)

# Replace the line defining the program
ado1_lines <- gsub(
  pattern = "^program define pystacked1, eclass$",
  replacement = "program define pystacked2, eclass",
  x = ado1_lines
)

ado1_lines[4] <- 
  "*! pystacked2 = uses python code appended to the file"
ado1_lines[5] <- 
  ""
ado1_lines[7] <- 
  "// do not edit this file manually; edit python1.ado, then run R script"

ado1_lines <- gsub(
  pattern = "//\\s*load core python code",
  replacement = "/* // load core python code",
  x = ado1_lines
)

ado1_lines <- gsub(
  pattern = "//\\s*end load core python code",
  replacement = "*/ // end load core python code",
  x = ado1_lines
)


# Read the contents of pystacked.py
py_lines <- readLines(pyfile, warn = FALSE)

# Combine the modified ado content with the Python code
output_lines <- c(ado1_lines, 
                  "", 
                  "* --- Python code appended below ---",
                  "python:",
                  py_lines,
                  "end")

# Write to pystacked2.ado
writeLines(output_lines, ado2)

cat("✅ pystacked2.ado created successfully.\n")
